# Generated by Django 3.0 on 2022-11-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='keyword',
            field=models.CharField(default='', max_length=50),
        ),
    ]
